name: Update godoc

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Update doc
      run: env GOPROXY=https://proxy.golang.org GO111MODULE=on go get -t -u github.com/elderica/golay@latest
